source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in luca-deal.gemspec
gemspec
gem "luca", git: "https://github.com/chumaltd/luca.git"
