#!/usr/bin/ruby
# frozen_string_literal: true

require 'optparse'
require 'curses'
require 'luca_term'

include Curses

init_screen
curs_set(0)
noecho

class LucaCmd
  def self.book(args, params = {})
    begin
      window = Curses::Window.new(0, 0, 0, 0)
      LucaTerm::Book.journals(window, *ARGV)
    ensure
      close_screen
    end
  end
end

cmd = ARGV.shift
params = {}

case cmd
when /book/, 'b'
  LucaCmd.book(cmd, params)
end
