#!/usr/bin/ruby
# frozen_string_literal: true

require 'optparse'
require 'curses'
require 'luca_book/journal'
require 'luca_term'

include Curses


class LucaCmd
  def self.book(args, params = {})
    init_screen
    curs_set(0)
    noecho

    begin
      window = Curses::Window.new(0, 0, 1, 0)
      args = ARGV.empty? ? LucaBook::Journal.latest_month : ARGV
      LucaTerm::Book.journals(window, *args)
    ensure
      close_screen
    end
  end
end

cmd = ARGV.shift
params = {}

case cmd
when /book/, 'b'
  LucaCmd.book(cmd, params)
end
