#!/usr/bin/ruby
# frozen_string_literal: true

require 'optparse'
require 'luca_salary'
require 'luca_salary/monthly'

def export(args = nil, _params = nil)
  if args
    args << 28 if args.length == 2 # specify safe last day
    LucaSalary::Monthly.new(args.join('-')).export_json
  else
    LucaSalary::Monthly.new.export_json
  end
end

def payment(args = nil, _params = nil)
  if args
    args << 28 if args.length == 2 # specify safe last day
    LucaSalary::Base.new(args.join('-')).calc
  else
    LucaSalary::Base.new.calc
  end
end

def report(args = nil, params = nil)
  if args
    args << 28 if args.length == 2 # specify safe last day
    LucaSalary::Monthly.new(args.join('-')).report(params.dig('mode'))
  else
    LucaSalary::Monthly.new.report(params.dig('mode'))
  end
end

def add_person(args = nil, _params = nil)
  LucaSalary::Profile.gen_profile!(args.first)
end

cmd = ARGV.shift

case cmd
when 'add'
  add_person(ARGV)
when 'export'
  export(ARGV)
when 'report'
  params = {}
  OptionParser.new do |opt|
    opt.banner = 'Usage: luca-salary report [--mail] year month [date]'
    opt.on('--mail', 'send to managers') { |_v| params['mode'] = 'mail' }
    args = opt.parse(ARGV)
    report(args, params)
  end
when 'payment'
  params = {}
  OptionParser.new do |opt|
    opt.banner = 'Usage: luca-salary payment [--mail] year month [date]'
    opt.on('--mail', 'send to managers') { |_v| params['mode'] = 'mail' }
    args = opt.parse(ARGV)
    payment(args)
  end
else
  puts 'Invalid subcommand'
end
